### ISSUE TITLE
Enhance FOLIO instance -> MARC mapping to include identifiers 

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#1047]
We want to map FOLIO instance identifiers to some MARC fields. We're hoping we can look at the format of the identifier string and map it into appropriate fields:

- [x] LCCNs `010a`: `%r{^(([ a-z]{3}\d{8})|([ a-z]{2}\d{10})) ?|( /.*)?$}`
- [x] ISBNs `020a`: `/^\d{9}[\dX].*/`, `/^(978|979)\d{9}[\dX].*/`, or `/^\d{12}[\dX].*/`
- [x] ISSNs `022a`: `/^\d{4}-\d{3}[X\d]\D*$/`
- [x] OCLC numbers `035a`: starts with `(OCoLC-M)` or `(OCoLC)`

(We're hoping to avoid resolving the identifierTypeId into the actual types, unless and until we actually need that data for something else.. our indexing for the fields is entirely pattern based so everything should map as expected without looking at the type names)

**Comment by thatbudakguy** [comment]
The first regex seems to be able to match zero-length space at the end of anything:
```ruby
>>> %r{^(([ a-z]{3}\d{8})|([ a-z]{2}\d{10})) ?|( /.*)?$}.match? 'garbage'
true
>>> %r{^(([ a-z]{3}\d{8})|([ a-z]{2}\d{10})) ?|( /.*)?$}.match 'garbage'
<MatchData "" 1:nil 2:nil 3:nil 4:nil>
```

**Comment by cbeer** [comment]
That's the regex we've always used 🤷‍♂️ 
https://github.com/sul-dlss-deprecated/solrmarc-sw/blame/6376b9472f7705d55617ea7200d69bd6583a03fa/stanford-sw/sw_index.properties#L192

**Comment by thatbudakguy** [comment]
Based on [the OCLC docs](https://www.oclc.org/bibformats/en/0xx/010.html#:~:text=After%20December%202000%2C%20LCCNs%20consist,a%20six%2Ddigit%20serial%20number.), I'm going to use `/^([ a-z]{0,3}\d{8} |[ a-z]{0,2}\d{10})$/`. I think the final portion of the original regex is wrong.

**Comment by thatbudakguy** [comment]
Do we care about looking for OCLC numbers starting with `on` too, or will there always be one with the `(OCoLC` prefix?

![Screenshot 2023-08-08 at 15 58 36](https://github.com/sul-dlss/searchworks_traject_indexer/assets/4924494/686725be-183d-4e0e-a26f-8a1ef7b52701)

**Comment by cbeer** [comment]
Those are the only two patterns we're using from the 035:
https://github.com/sul-dlss/searchworks_traject_indexer/blob/main/lib/traject/config/sirsi_config.rb#L940-L946

**Comment by cbeer** [comment]
Looking at the actual data, I think the existing regex is important for values like

```
   68038902 //r84
```
