### ISSUE TITLE
current_location field in `item_display_struct` should be the FOLIO code if we can't map it to a Symphony code for parity

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#1068]
We're currently lopping the library prefix off (somehow?), which breaks the downstream location mapping code for locations without a symphony equivalent (e.g. `SUL-TS-CC-REPAIR` should display in Searchworks as "Out for repair" instead of "TS-CC-REPAIR")

https://searchworks-folio-dev.stanford.edu/view/12278435
![Image](https://github.com/sul-dlss/searchworks_traject_indexer/assets/111218/4d6d286d-2b99-4081-9d7f-cc4c10f6c608)

**Comment by corylown** [comment]
It's happening because it's mapped in the `temp_locations.tsv` file: https://github.com/sul-dlss/searchworks_traject_indexer/blob/main/lib/translation_maps/temp_locations.tsv#L49

Maybe codes in this file shouldn't get mapped?

**Comment by cbeer** [comment]
Ah ha. Unfortunately, I think we want some of those codes. 🤔

**Comment by thatbudakguy** [comment]
More analysis needed to figure out if we can know which codes we want to map.

**Comment by corylown** [comment]
Added some analysis to a Google Sheet: https://docs.google.com/spreadsheets/d/16g5pm8sZpbSl7Kvlk528Rw_VIWB7mAoWiWKsyE6rWSM/edit#gid=0

I think the ones that are problematic are (because they're mapped to a current location without the library code prefix, but don't have Sirsi equivalent):

```
ARS-WD-DIGITAL-SUB
ART-WD-DIGITAL-SUB
BUS-WD-DIGITAL-SUB
CLA-WD-DIGITAL-SUB
EAL-WD-DIGITAL-SUB
EAR-WD-DIGITAL-SUB
EDU-WD-DIGITAL-SUB
ENG-WD-DIGITAL-SUB
GRE-WD-DIGITAL-SUB
LAW-WD-DIGITAL-SUB
MAR-WD-DIGITAL-SUB
MEDIA-WD-DIGITAL-SUB
MUS-WD-DIGITAL-SUB
RUM-WD-DIGITAL-SUB
SAL-WD-DIGITAL-SUB
SAL3-WD-DIGITAL-SUB
SCI-WD-DIGITAL-SUB
SUL-TS-MAINTENANCE
SUL-TS-PROCESSING
SUL-TS-COLLECTIONCARE
SUL-TS-CC-SPECIALPROJECTS
SUL-TS-CC-REPAIR
SUL-TS-CC-KASEMAKE
SUL-TS-CC-BOOKJACKET
SUL-TS-CC-BINDERYPREP
LAW-SHADOW-ORD
```

**Comment by corylown** [comment]
Yeah, I think with the changes I proposed we get this display for the example record:

<img width="393" alt="Screenshot 2023-08-14 at 4 23 35 PM" src="https://github.com/sul-dlss/searchworks_traject_indexer/assets/458247/26823344-482b-4a66-b4c6-d52509a34f70">

I'll put some PRs together for sw-traject-indexer and SearchWorks.
