### ISSUE TITLE
Use location/details information (`searchworksGovDocsClassification`) to map govdocs locations for `callnum_facet_hsim`

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#1075]
- [ ] update `folio-graphql` to expect a string property called `searchworksGovDocsClassification` on `Location.details`
- [ ] set the `searchworksGovDocsClassification` value for gov doc locations in FOLIO according to the translation map (see below)
- [ ] update the logic for `SirsiHolding#gov_doc_loc?` to use the location details instead of `GOV_DOC_LOCS`
- [ ] update the indexer to use the value of `searchworksGovDocsClassification` in the call number facet
- [ ] extract the handling of marc 086 values to its own separate `to_field` definition (optional)

**Comment by thatbudakguy** [comment]
We add extra information to the call number facet for government documents in a special block: https://github.com/sul-dlss/searchworks_traject_indexer/blob/854f92a6d6efa195313b4885c7202a7bcb2e8662/lib/traject/config/sirsi_config.rb#L1924-L1962

Right now, this is controlled via a hardcoded list of govdoc locations:
https://github.com/sul-dlss/searchworks_traject_indexer/blob/854f92a6d6efa195313b4885c7202a7bcb2e8662/lib/sirsi_holding.rb#L104-L106

And a translation map for getting a human-friendly label for the type of docs in each location:
https://github.com/sul-dlss/searchworks_traject_indexer/blob/854f92a6d6efa195313b4885c7202a7bcb2e8662/lib/translation_maps/gov_docs_locations.properties#L1-L9
