### ISSUE TITLE
Figure out what to do about the backlog of MARC21 + MARCXML-formatted records used for testing

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#1113]
We're carrying around a lot of MARC21 + MARCXML data used in the tests converted from solrmarc. We're moving away from MARC21 + MARCXML in our indexer (FOLIO uses a JSON representation internally), so it's probably time to do something about this data, e.g.

- build on-demand MARC data (or Folio record instances) for unit testing specific scenarios
- be a little smarter about generating MARC data used for the shotgun "what happens if we map X" tests  
- rewrite tests to test specific records instead of "run the file through the indexer and pluck out particular documents" approach
- convert remaining MARC21/MARCXML to the MARC JSON schema FOLIO uses

**Comment by jcoyne** [comment]
There are 1101 instances of `select_by_id` in the tests where the "pluck out particular documents" approach is used.
