### ISSUE TITLE
Fix MHLD sorting for selecting the latest

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#1237]
Problematic examples:
https://searchworks.stanford.edu/view/364046
https://searchworks.stanford.edu/view/10694200 

VUF-9321
SW-4180

**Comment by cbeer** [comment]
`Date.parse` is a little to... eager.. to extract some date:

```https://github.com/sul-dlss/searchworks_traject_indexer/blob/main/lib/folio/holdings.rb#L36

**Comment by thatbudakguy** [comment]
Could be helpful to have a real database dump of enum/cron values so that we know the full scope of how bad/weird the data can be.

**Comment by hudajkhan** [comment]
Closed by #1265
