### ISSUE TITLE
ISO 19110 should be included in the geoblacklight references

### ISSUE THREAD

**Issue by drh-stanford** [sul-dlss/searchworks_traject_indexer#1300]
we're not including the 19110 feature catalog pointer in the geoblacklight dct_references_s. it should point to the OpenGeoMetadata copy.

**Comment by thatbudakguy** [comment]
example map: https://earthworks.stanford.edu/catalog/stanford-mb303sh3837
in our OGM repo: https://github.com/OpenGeoMetadata/edu.stanford.purl/tree/master/mb/303/sh/3837

see also the OGM documentation on how `dct_references_s` is formatted: https://opengeometadata.org/configure-references-links/

**Comment by thatbudakguy** [comment]
this should probably look similar to how we link to the ISO19139 already in the indexer:
https://github.com/sul-dlss/searchworks_traject_indexer/blob/2e065a507a58275a9f53e3e759e00d43e198255d/lib/traject/config/geo_config.rb#L308
