### ISSUE TITLE
Poppy upgrade: Investigate using `instance.complete_updated_date` to replace instance/holdings/items join

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#1332]
Possibly fixes https://github.com/sul-dlss/searchworks_traject_indexer/issues/980

**Comment by hudajkhan** [comment]
Seems like: Poppy added field for timestamp on instance reflecting whether holdings/items have changed.
We need to assess if that is in fact true, and then see if we can use the Poppy info to save some indexing work.

**Comment by dnoneill** [comment]
https://github.com/sul-dlss/searchworks_traject_indexer/pull/1310

**Comment by dnoneill** [comment]
changing properties on the instance
changing properties on a holdings record
changing properties on an item
transferring an item between holdings
transferring a holdings record between instances
and things to test that probably don’t work:
changing marc records
changing course reserves information

**Comment by dnoneill** [comment]
Couple of things that came up with exploring the data:

| table | Number of rows per table | How to access instance |
| --- | --- | --- |
| sul_mod_inventory_storage.instance | 10,284,710 | n/a |
| sul_mod_inventory_storage.holdings_record | 12,366,458 | instanceid field |
| sul_mod_inventory_storage.items | 11,429,559 | holdingsrecordid field |

One odd thing about the holdings_record is there doesn't seem to be any empty instanceid fields (assuming I queried correctly) which makes me think a couple of holding records have the same instance id?
