### ISSUE TITLE
Separately index license/use/copyright for geo

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/searchworks_traject_indexer#1437]
Currently we're indexing rightsMetadata xml and parsing this in Earthworks. Instead, index these as separate fields.  See:
https://github.com/sul-dlss/earthworks/blob/72615ab262eec2604def30dcb3991c80b0afa092/lib/rights_metadata.rb#L4

**Comment by thatbudakguy** [comment]
This may be fully resolved by #770 – Aardvark provides several new fields for these purposes, and we might be able to map each of them accordingly.

**Comment by thatbudakguy** [comment]
Resolved by #770
