### ISSUE TITLE
[draft] decouple from isConstituentOf

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/searchworks_traject_indexer#1447]
isConsitutentOf is a challenge to produce because this inverts the relationship from the source data.  In the cocina, the parent stores the relationship.  In the MODS the children store the relationship to the parent.

The indexing is here:
https://github.com/sul-dlss/searchworks_traject_indexer/blob/main/lib/traject/config/sdr_config.rb#L326-L334

It is used by searchworks in this module https://github.com/sul-dlss/SearchWorks/blob/fdd7f22488ba78109885d53683355fde3b58309f/app/models/concerns/solr_set.rb#L7

Could we instead index the members on the parent which would mirror the source data and adjust Searchworks to use the new field stored on the parent?

**Comment by cbeer** [comment]
It seems like that would create one really big Solr field and require us to always query solr to find out if an object even has a set. I suspect one or both of those could have a performance impact.
