### ISSUE TITLE
Do not index geo material without a bounding box

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/searchworks_traject_indexer#1504]
In the old config, we skipped records that did not have valid coordinates in the `solr_geom` field:
https://github.com/sul-dlss/searchworks_traject_indexer/blob/4ed5e9e8fee1100b26d4c48262e91dcbfa66fc47/lib/traject/config/geo_config.rb#L465-L475

In the new config, there are two fields, `locn_geometry` and `dcat_bbox`. Because we always use the same `ENVELOPE` syntax for both, we populate `locn_geometry` and then set `dcat_bbox` to the same value as `locn_geometry`, since they will never differ (for Stanford records, anyway).

Currently, we allow both fields to be empty, because [the spec](https://opengeometadata.org/ogm-aardvark/#bounding-box) for Aardvark has both as "suggested" fields rather than required. This is a departure from the v1 schema, which required a bounding box.

As per discussion at the GIS team meeting 8/12, we don't think it's useful to support having content with no geospatial information at all (bounding box or geometry) in Earthworks, even if the spec allows it. Thus, we want to bring back the behavior from the old config of skipping these records and publishing a warning message to SDR to indicate that they were skipped because of a lack of valid coordinates.

To do this, we can insert an `each_record` block that skips records with no `locn_geometry` (no need to check `dcat_bbox` since they will always be identical). The block can either come immediately after the field definition or at the end. It'll probably look pretty similar to the block from the old config linked above.

**Comment by thatbudakguy** [comment]
No need to worry about any existing items that were indexed without geometry; we are planning a full reindex that will take care of that as long as this ticket is completed beforehand.

**Comment by marlo-longley** [comment]
@kimdurante hi! Is it possible for you to share an example record that falls into this category? Thank you.

**Comment by kimdurante** [comment]
@marlo-longley Here is one: [https://earthworks.stanford.edu/catalog/stanford-cd502cx8669](https://earthworks.stanford.edu/catalog/stanford-cd502cx8669)
