### ISSUE TITLE
Guard against empty cocina timestamps

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/searchworks_traject_indexer#1512]
Some of the logic in the geo indexing config uses a series of fallbacks to generate a "modified date" for the metadata itself:
https://github.com/sul-dlss/searchworks_traject_indexer/blob/bbb0e6c0d98d829824946925335e3f2a6ccb797c/lib/traject/config/geo_aardvark_config.rb#L260-L265

Releasing the object `cb601kb6593` from argo-stage will throw the following error in the event log:
```json
{
  "host": "sw-indexing-stage-a.stanford.edu",
  "target": "Earthworks",
  "context": {
    "record": "<record #1 (/dev/null #1), output_id:stanford-cb601kb6593>",
    "index_step": "(to_field \"gbl_mdModified_dt\" at ./lib/traject/config/geo_aardvark_config.rb:264)"
  },
  "message": "no implicit conversion of nil into String",
  "invoked_by": "indexer"
}
```

**Comment by thatbudakguy** [comment]
I've republished many staging objects that trigger this, but some don't appear to be generating new cocina and will still throw errors, e.g. [km361zq1607.](https://sul-purl-stage.stanford.edu/km361zq1607)

**Comment by jcoyne** [comment]
@thatbudakguy In the event log for that item, we see "Publish request received" but never "Publish complete", so it' never republished with good data.

**Comment by thatbudakguy** [comment]
I saw that too. Any idea why?

**Comment by lwrubel** [comment]
I think this can be closed, based on what we learned about the version needing to be closed for these particular objects?
