### ISSUE TITLE
Update LOC Call Number translations

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/searchworks_traject_indexer#189]
Need to update our translations for LOC call numbers. ie DX - Gypsies (History) should now be Romanies. 
**See comment below for updated mapping**

From jira 
**_We want to suppress any call number that does not have a translation_**

"Ruth Tillman passes on this message from the code4lib slack:
> Morning, folks. I was reading (shamelessly copying/proofing/adapting) Princeton’s call number map.and noticed that DX is still listed as “DX - Gypsies (History)“. Although the Library of Congress has been slower to act on some issues of racial terms which are often used/construed as slurs, they actually caught up on this one and made the change to “Romanies.” It’s on page 2 of the PDF linked below.: https://www.loc.gov/aba/cataloging/classification/lcco/lcco_d.pdf"

https://jirasul.stanford.edu/jira/browse/SW-1939

**Comment by jkeck** [comment]
We will most likely want to coordinate this w/ a full-reindex of MARC data.

**Comment by cbeer** [comment]
Where is the updated mapping?

**Comment by ahafele** [comment]
@jvine or @shelleydoljack probably know.

**Comment by jvine** [comment]
[call_number_translations_reviewed_vct_20180709.txt](https://github.com/sul-dlss/searchworks_traject_indexer/files/2407111/call_number_translations_reviewed_vct_20180709.txt)

These are in call number order. I seem to remember they were ordered with more-specific call numbers first in the original (e.g. DAW before DA before D) so they may need reordering.
