### ISSUE TITLE
Add genre to genre facet

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/searchworks_traject_indexer#222]
genre_ssim should include genre

**Comment by cbeer** [comment]
Instead of, or in addition to, the current genre processing for Thesis/Dissertation, Conference proceedings, Government document, and Technical report?

**Comment by arcadiafalcone** [comment]
In addition to.

**Comment by cbeer** [comment]
I want to double-check before I change a bunch of tests...

If we have a record with:

```
<genre authority="marcgt">Conference Publication</genre>
```

you want us to produce two `genre_ssim` values:

- `Conference Publication` (from the genre value)
- `Conference proceedings` (current behavior)

**Comment by arcadiafalcone** [comment]
I checked with Gryphon Search and yes, we do want both terms, so that the "Conference proceedings" facet value will continue to contain both MARC and MODS data, and the actual metadata value "Conference Publication" will appear in the facet as well.
