### ISSUE TITLE
IIIF badge - Indexing tasks

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/searchworks_traject_indexer#243]
We need to identify which records should get an IIIF badge (see comment below) and add the manifest URL to a new field in the document.

We'll ultimately want to be able to query this in the app to create the resource access point. So either we need to be able to do some sort of query against the field to return documents w/ any value populated, or have some sort of facetable value (whichever makes sense)

**Comment by mejackreed** [comment]
Currently in embed, we support this by mods content_type lookup: 
https://github.com/sul-dlss/sul-embed/blob/cb380c4c18ad9d84783ef0469b85563ddfa200eb/app/viewers/embed/viewer/uv_image.rb#L8-L10

`[:image, :manuscript, :map, :book]`
