### ISSUE TITLE
Map old `format`  field

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#40]
Blocked pending investigation into whether we can update the library.stanford.edu links that may still be using this facet.

Split from #13

**Comment by mejackreed** [comment]
Did we get confirmation?

**Comment by cbeer** [comment]
@jvine did some research in the library drupal database, and found many that have the old format facet. It's possible we can find+replace on that end and call it good.

**Comment by mejackreed** [comment]
Recommendation from @jvine that we do _not_ continue supporting this legacy field. OEG will handle this migration for lib website.
