### ISSUE TITLE
MODS, author sort and capitalization of the relator term

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/searchworks_traject_indexer#510]
Hannah reported that, after searching for a collection, she used the "sort by" and selected author but the results list failed to sort the results list alphabetically by last name.

Example search: https://searchworks.stanford.edu/?f%5Bcollection%5D%5B%5D=qf495kg6879&sort=author&view=list

Jessie did some looking and reported:
The issue, at least w/ the collection that is reported here, (or at least one of the issues) is that the author relator terms are not capitalized which is what is expected by the stanford-mods gem for identifying main authors.

This is causing the author sort field to have a different author than is being displayed as the first/main author in the record.

As an example, here are the first 3 records currently showing up for this result (and the author that is being sorted on):
kg477dc3533: Crawford Vincent
jc844vf0304: Gunning Jan Willem
bw479pd2422: Schjerning Bertel

This is because when a relator with "Author" or "Creator" role is not present it selects the first name w/o a role as the main author.

At the 5th record in the result set we no longer have name's w/o roles, so we no longer have an author in the sort field and we begin the title sub-sort.

If the roles are updated in these records to be correctly capitalized as described https://id.loc.gov/vocabulary/relators.html then I believe the sort will be updated appropriately.

For what it's worth, it would also be possible to update the stanford-mods gem to be more permissive of the capitalization of the relator term (I already have a [small change](https://github.com/sul-dlss/stanford-mods/compare/allow-mix-cased-name-marcrelators) that I could propose), however we might also want to figure out what part of our process is generating invalid relator terms into the MODS.

**Comment by jkeck** [comment]
This was addressed in sul-dlss/stanford-mods#113.  This search result should be fixed on our next full re-index (or the items in the SITE collection could be re-published, or whatever would trigger the re-index of them).
