### ISSUE TITLE
"nomesh" in 655a is getting indexed. Also add "nomeshx"

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/searchworks_traject_indexer#550]
Reports from staff that "nomesh" in the 655a is being indexed and displayed in SearchWorks.  We should be rejecting this as a subject heading, as it's used internally by Lane folks.

Additionally, we're seeing "nomeshx" and that should be added to the rejection.

I also noticed [here ](https://github.com/sul-dlss/searchworks_traject_indexer/blob/49fd059d3b77de31ddb1435cdc6645f1f02837a7/lib/traject/config/sirsi_config.rb#L874) that we're specifically looking for LANE-MED in the 999, but a [SearchWorks search](https://searchworks.stanford.edu/?f%5Bbuilding_facet%5D%5B%5D=Green&q=nomesh&search_field=search) reveals a few records in Green/SAL/SAL3.  Data Control confirmed that we shouldn't index or display "nomesh" or "nomeshx" on any record.

Most recent Jira issue: https://jirasul.stanford.edu/jira/browse/SW-3977

**Comment by cbeer** [comment]
Just spot-checking, a lot of the records in that search have the 650a of `nomesh.` (with a period). Is that a data control issue, or do we need to do something more (starts with `nomesh`?)?

**Comment by saseestone** [comment]
we should add 650a and "nomesh." to the suppression list.
