### ISSUE TITLE
Figure out which mapping for dept_code_2_user_str is correct

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/searchworks_traject_indexer#60]
`GERGEN` and `ILAC` are both used twice. This is an open question about which value is correct.

cc @jvine @shelleydoljack 

https://github.com/sul-dlss/crez-sw-ingest/blob/master/config/dept_translations.rb#L87-L89
https://github.com/sul-dlss/crez-sw-ingest/blob/master/config/dept_translations.rb#L95-L131

**Comment by shelleydoljack** [comment]
I don’t think we use the department names for anything. I think this was meant to be used at some point but never implemented.

**Comment by jvine** [comment]
ILAC really is used twice. GERGEN isn't on this list. http://explorecourses.stanford.edu/  Agree with Shelley, I don't think we're actually using these anywhere.

**Comment by shelleydoljack** [comment]
Oh, nevermind my comment above. I see the field in the schema. My guess is that we should probably update these translations with whatever the latest is from explore courses.
