### ISSUE TITLE
draft data specification for record export from FOLIO

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/searchworks_traject_indexer#639]
# background
with the move to FOLIO, we need to re-evaluate the record format currently produced by [ExportSearchWorks](https://github.com/sul-dlss/ExportSearchWorks) via querying Symphony APIs. these records are picked up by traject and used to generate the solr documents that power SearchWorks. for an overview of how this happens, see [MARC extract from Symphony](https://docs.google.com/document/d/1pliBFylvLqWPVO1xZtZ8SFW_9KzUsn0hYmJ1G5F6ADU/edit?usp=sharing) (google doc).

part of the transition process will also be decommissioning ExportSearchWorks, so individual parts of its business logic might move to Airflow DAGs, into FOLIO workflows, or into [searchworks-traject-indexer](https://github.com/sul-dlss/searchworks_traject_indexer). understanding the type of records that we need to generate will help inform this process.

we also could cease using binary marc as an export format and move to JSON or another friendlier record type, since FOLIO exports are JSON and there's no particular reason traject needs to consume binary marc. 

a rough overview of what we would (ideally) pass to traject, via @cbeer:
<pre>
 for each bib record:
   get the bib record out of SRS,
   merge in all the holdings,
   merge in all the <s>instance</s> item data,
   merge in any reserves data,
   merge in a mapping of UUID => { short id, label, ?? }  for libraries, locations, item types, etc
</pre>

this would result in a record that gives traject all it needs to construct a solr document capable of powering discovery in SW, and delivery/access via requests and course reserves.

much of this merge work is currently happening in traject-land now.
# questions
- [x] how do we get bib data out of FOLIO?
  - using the source record storage API?
  - using the source record streaming API, since it's maybe faster?
- [x] how do we get holdings data out of FOLIO?
  - using the holdings storage API
- [x] how do we get <s>instance</s> item data out of FOLIO?
  - <s>we get it for free when calling the holdings storage API as `holdingsItems`</s> not intended for production use 😢 
  - using the item storage API, supplying the relevant holdings UUID
- [ ] how do we get reserves data out of FOLIO?
  - see https://github.com/sul-dlss/searchworks_traject_indexer/issues/667
- [x] should we move away from binary marc as an export format? if so, what should be the new format?
  - yes, we should use regular JSON as the new format
- [x] #644
  - map UUIDs to more human-friendly values for libraries, locations, item types, etc.
  - remove staff info https://github.com/sul-dlss/searchworks_traject_indexer/issues/662

**Comment by cbeer** [comment]
>  should we move away from binary marc as an export format? if so, what should be the new format?

Yes. I think we should plan on working with JSON records.

**Comment by thatbudakguy** [comment]
bib data: probably using SRS Streaming API, as in [this example notebook](https://gist.github.com/jermnelson/bf8e78fdb9675cd877686cd26d253c5a), partly for performance reasons

holdings data: probably using [holdings storage API](https://s3.amazonaws.com/foliodocs/api/mod-inventory-storage/p/holdings-storage.html), so long as we can later transform its UUIDs into more useful values

**Comment by shelleydoljack** [comment]
We are using [folio_migration repo](https://github.com/sul-dlss/folio_migration) to map our data to the FOLIO formats. Maybe looking at the mapping files might bring some stuff to light. 

Also, I think you mean "items" instead of "instances" in the above comments. FOLIO instances equate to title/instance-level description, like MARC bibliographic data.

```
{
  "sourceRecord": { },
  "holdingsRecords": [],
  "items": [],
}
```
Would the field "sourceRecord" contain the MARC in JSON or would it look like what we get from the SRS streaming API? Would the holdingsRecords and items contain those objects as they are coming out of FOLIO or would they be processed in some way before handing off to traject?

**Comment by cbeer** [comment]
I guess holdingRecords and items are redundant? https://s3.amazonaws.com/foliodocs/api/mod-inventory-storage/p/holdings-storage.html#holdings_storage_holdings__holdingsrecordid__get seems to include both

**Comment by thatbudakguy** [comment]
@shelleydoljack thanks for the terminology correction! i edited the top post for clarity.

**Comment by cbeer** [comment]
> Would the field "sourceRecord" contain the MARC in JSON or would it look like what we get from the SRS streaming API? 

I think the whole output of e.g. https://s3.amazonaws.com/foliodocs/api/mod-source-record-storage/p/source-record-storage-records.html#source_storage_records__id__get would be useful in some way. I'm not sure what the SRS streaming API provides.

**Comment by thatbudakguy** [comment]
closing this ticket since we're pretty confident in our JSON record structure in traject now and the remaining questions have their own tickets (linked in top comment).
