### ISSUE TITLE
Convert eye-managed processes to use foreman instead

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#643]
`eye` is giving us some grief deploying under ruby 3.x (hanging processes, unable to find `eye` binary, etc). Now that we're in a systemd environment, maybe user-level systemd scripts are the way to go?

See #632 for an example of the weird kind of errors that come up.

**Comment by thatbudakguy** [comment]
Blocked on https://github.com/sul-dlss/puppet/pull/9493
