### ISSUE TITLE
Preprocess FOLIO bib + item data to remove staff information

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#662]
Note: It's unclear how much of the symphony cleanup is applicable to FOLIO.

Original source:
https://consul.stanford.edu/display/SYSTEMS/Data+Feed+to+SearchWorks

- [x] remove "junk tags" <details><summary>(full list)</summary>
001
003
004
005
852
853
863
866
867
868
901
910
918
923
924
930
935
940
948
949
950
955
960
962
980
981
983
990
993
998
999
</details>

- [x] validate whether we use the 916 tag directly in searchworks (not present in FOLIO, using separate mapping for date_cataloged)
- [x] Price stripped for item records (was in 999 $p; unknown FOLIO equivalent, if any)
- [x] Date/time of export: Date added to 005 field (validate whether it is use for anything)

**Comment by thatbudakguy** [comment]
it sure doesn't look like we're using the 005 field. i can't find any traject fields defined for it, and while our MARC fixture data has it, there doesn't appear to be anywhere referencing that data. if we later decided we needed it, we could maybe do something clever with the `last_response_date` that the `FolioClient` knows.

**Comment by thatbudakguy** [comment]
re: price i think this is unrelated in FOLIO. the only place that information seems like it's available is through the [PO Line API](https://docs.folio.org/docs/acquisitions/orders/#cost-details), and I don't even know how or whether item records are linked to the POs that acquired them.

**Comment by thatbudakguy** [comment]
re: `date_cataloged`, we [use it in SW](https://github.com/sul-dlss/SearchWorks/blob/6bb2822c835203fb436208b6e8e0c2dd03eae803/app/controllers/catalog_controller.rb#L453) to power sorting by that value, which looks like this:


![Image](https://user-images.githubusercontent.com/4924494/182722348-4265dd82-6a51-4a2e-8a30-a6a9f60fd021.png)

it looks like values in that field are already iso8601 timestamps like `2022-08-02T00:00:00Z`, so I think we're good there. i don't think we can control this value in FOLIO though, so it might lead to a little bit of weirdness after the migration, when everything in the catalog effectively has the same (or close to the same) "catalog date" (i.e. the point at which the record was migrated into FOLIO).

**Comment by cbeer** [comment]
> it might lead to a little bit of weirdness after the migration, when everything in the catalog effectively has the same (or close to the same) "catalog date"

I wonder if we should raise this with @saseestone (or one of the gryphon-*s?) to make sure we understand the consequences of not migrating the 916 data?

**Comment by shelleydoljack** [comment]
> i don't think we can control this value in FOLIO though, so it might lead to a little bit of weirdness after the migration, when everything in the catalog effectively has the same (or close to the same) "catalog date" (i.e. the point at which the record was migrated into FOLIO).

This should be considered a data migration issue. I don't know what decisions have been made in whatever subgroup (presumably Metadata) regarding mapping the date cataloged to a field in FOLIO. @ahafele

**Comment by shelleydoljack** [comment]
> it sure doesn't look like we're using the 005 field.

That's correct, it's not "used" by any code, just people when they view records in Librarian View. I see some records in FOLIO have an 005 field, like a2719415, but it looks like the date when that particular record was exported from the GPO and imported into Symphony (i.e. it's not the real [datetime of latest transaction](https://www.loc.gov/marc/bibliographic/bd005.html)) . I think maybe doing something in traject, like inserting an 005 for datetime record was pulled from FOLIO, is the way to go for populating this field.

**Comment by shelleydoljack** [comment]
Hmm, i think I accidentally closed this issue... reopening..

**Comment by thatbudakguy** [comment]
closing this since:
- junk tags are now stripped (#684); we can revisit as necessary
- `date_cataloged` is populated; discussions about how to make it a more real/correct date are in-progress but would likely have to happen as part of the migration, so outside the scope of this issue
- price doesn't need to be stripped because it's not in the FOLIO MARC
- date/time of export is available in the solr `last_updated` field which you can view in the JSON view (e.g. https://searchworks.stanford.edu/view/14185251.json); if we want to put that information into the MARC or a different place, we can open a new ticket to do that
