### ISSUE TITLE
Handle FOLIO deletes in the indexer

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#663]
When a record is deleted from FOLIO (or marked as suppressed from discovery? or becomes otherwise invalid?), the record should be removed from Solr.

**Comment by thatbudakguy** [comment]
still grappling with FOLIO's distinction between instance record and source record, but it seems like it's important to understand in the context of deletes. to my knowledge:
- instance records are FOLIO's concept of a bib; they [cannot be deleted — only suppressed](https://docs.folio.org/docs/metadata/inventory/#deleting-an-instance-record). it's possible to [create an instance record entirely within FOLIO](https://docs.folio.org/docs/metadata/inventory/#administrative-data) without ever interacting with any MARC, in which case it won't have a source record (its source is `FOLIO`, as opposed to `MARC` or `EPKB`).
- source records are the actual MARC that was used to create an instance record. unclear if some properties of the instance record effectively delegate to its source record, or vice versa. there are a variety of ways to indicate that a source record is deleted.

for source records (MARC) at the `/source-storage/stream/source-records` endpoint:
- you can filter by `suppressFromDiscovery`. maybe this references the associated instance record?
- you can filter by `deleted`. this checks if:
  - the state of the record is `DELETED`
  - the state of the record is `ACTUAL` (?)
  - the MARC leader 05 is set to `d`, `s`, or `x`. marc21 provides [`d` as "deleted"](https://www.loc.gov/marc/bibliographic/bdleader.html); unclear what `s` or `x` are for (or if they're valid MARC).

**Comment by thatbudakguy** [comment]
old PR? https://github.com/sul-dlss/searchworks_traject_indexer/pull/707

**Comment by thatbudakguy** [comment]
we need to confirm (with @ahafele) how records are "deleted" (marked suppressed, MARC edited, etc.) in FOLIO now so that we can cover all the cases and find some records to test with.

**Comment by ahafele** [comment]
Right now records will be "deleted" by marking them as suppressed at the Instance level. Here is an example - https://folio-test.stanford.edu/inventory/view/0c7e5994-fce7-5a85-a715-384146ec3d3f 
You are welcome to mark additional records as suppressed for further testing or if you prefer I can grab a test set, mark them for SW testing and then mark them all as suppressed - any other criteria to consider? 

We may consider adding a stat code for DELETE, but I assume SW only cares about suppression and not the reason for suppression. In the future there will be an explicit "mark for deletion" flag but not in Nolana.

Open related question on our end - how will SW handle instance records with ALL items suppressed - will it assume suppression at the instance level or will it need to be explicit?

**Comment by cbeer** [comment]
> Open related question on our end - how will SW handle instance records with ALL items suppressed - will it assume suppression at the instance level or will it need to be explicit?

I think we'd strongly prefer explicit suppression, especially now that some instances (on-order, electronic, mhlds) are expected to lack items.

**Comment by jcoyne** [comment]
Test plan:
* find a record in https://searchworks-folio-dev.stanford.edu/
* mark it suppressed in folio-test
* after 15 minutes (Solr autocommit delay) ensure it can no longer be found in https://searchworks-folio-dev.stanford.edu/

**Comment by jcoyne** [comment]
Executed test plan:
* Record https://searchworks-folio-dev.stanford.edu/view/14598667
* Marked suppressed in https://folio-test.stanford.edu/inventory/view/fb9341f5-7fc9-5a7a-b608-7d341768e7ce?qindex=hrid&query=a14598667&sort=title  at 12:07 PDT 5/2/2023
* Monitoring: https://searchworks-folio-dev.stanford.edu/view/14598667
