### ISSUE TITLE
Index records that only have instance data (no SRS data)

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#681]
- [ ] course reserves data that "catalog" an instructor copy
- [ ] on-order acq without MARC records
- [ ] equipment?

Is there a way to get MARC data for this, or do we have to deal with inventory/instance JSON data

**Comment by thatbudakguy** [comment]
@ahafele will create an on-order acq without MARC records and an equipment record for testing.

**Comment by saseestone** [comment]
Getting an error today when trying to add any Fast Add item (from Courses app or Inventory app). Will report in folio-support channel too.

**Comment by ahafele** [comment]
I'm unable to create "on-order acq without MARC records and an equipment record" at the moment because Inventory is not working correctly. I will try again once those issues are resolved.
