### ISSUE TITLE
Run performance tests from sw-indexing-dev

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#69]
... using the first 500k marc records? against an ephemeral collection in sul-solr (http://sul-solr-a.stanford.edu/solr/admin/collections?action=CREATE&name=EPHEMERAL-COLLECTION-NAME-GOES-HERE&numShards=1&replicationFactor=1&collection.configName=searchworks-dev)?

1) Capture a baseline with MRI ruby with (`NUM_THREADS=0`).

2a-h) Under jruby with permutations of these options:

- [x] NUM_THREADS=0
- [x] NUM_THREADS=1
- [x] NUM_THREADS=4
- [x] NUM_THREADS=8

- [ ] with traject_marc4j_reader (needs a change in the MarcCombiningReader + using master from https://github.com/traject/traject-marc4j_reader)
- [ ] with traject::marcreader (the default)

--

also, take note of CPU + RAM utilization.

**Comment by mejackreed** [comment]
Just writing this down so its noted:

Likely our indexing rate will be much less than sw-solr-g tests until we run parallelized traject processes with each `*.marc` file.

**Comment by mejackreed** [comment]
Basic MRI tests run. Continue to run into errors and failures w/ jruby deployed.

**Comment by mejackreed** [comment]
Results all finished and here: https://docs.google.com/spreadsheets/d/111KqKIOkPmw8HJ0YIkve4WqsDJkEje7M-xyueAJMng4/edit#gid=2089885854
