### ISSUE TITLE
Stop publishing PURL updates to Kafka

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/searchworks_traject_indexer#761]
Depends on https://github.com/sul-dlss/purl-fetcher/issues/562.

Once purl-fetcher is publishing its updates to kafka directly, there's no longer any need for the [`PurlFetcherReader`](https://github.com/sul-dlss/searchworks_traject_indexer/blob/master/lib/traject/readers/purl_fetcher_reader.rb) or  [`PurlFetcherKafkaExtractor`](https://github.com/sul-dlss/searchworks_traject_indexer/blob/master/lib/traject/extractors/purl_fetcher_kafka_extractor.rb). We also no longer need to run the [`process_purl_fetcher_to_kafka`](https://github.com/sul-dlss/searchworks_traject_indexer/blob/master/script/process_purl_fetcher_to_kafka.rb) script, so it can be removed and its cron job deleted.

**Comment by jcoyne** [comment]
Fixed by #764
