### ISSUE TITLE
Reindex records based on changes in non-instance data

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#766]
When data changes in FOLIO that effects the sesarchworks display, we want to reindex records to make sure data is accurated displayed. The most important changes are in the bibliographic metadata or location, and we previously used the updated times from:
- [x] `sul_mod_inventory_storage.holdings_record`
- [x] `sul_mod_inventory_storage.instance`
- [x] `sul_mod_inventory_storage.item` 
- [x] `sul_mod_source_record_storage.records_lb`

There is data from other tables that may receive impactful updates:  
- [x] `sul_mod_courses.coursereserves_reserves` provides start + end dates for reserves, connects an item to a course (72 rows)
- [x] `sul_mod_courses.coursereserves_courses` provides course name + number (48 rows)
- [x] `sul_mod_courses.coursereserves_courselistings` provides instructor info (42 rows)
- [ ] `sul_mod_orders_storage.pieces` provides MHLD info (23913 rows, there are no update times in this table)
 
There's also an opportunity to use labels from various tables instead of maintaining a code->user label mapping in Searchworks:
- [ ] `sul_mod_inventory_storage.location`  
- [ ] `sul_mod_inventory_storage.loclibrary`
- [ ] `sul_mod_inventory_storage.loan_type`

**Comment by thatbudakguy** [comment]
the current indexing implementation merges information from a ton of different tables, but it only looks at the `updatedDate` for instance/holding/item to decide if the record was changed.

we need to:

- [ ] determine what other fields changing constitutes a change (see above — reserve status, location name, etc). what would matter to a SearchWorks user when it gets changed?
- [ ] figure out if FOLIO is already doing any magic to bump the `updatedDate` when these things change?
- [ ] if not, ensure we can query the database for changes to those fields
- [ ] ...and if we can't query in the way we want because of the way the database is set up (likely), figure out what kind of constraints we need to enforce (e.g. you aren't allowed to rename locations and must make a new location)

**Comment by thatbudakguy** [comment]
possibly worth investigating if we can use some internal message queue parts of FOLIO to listen for changes instead of/in combination with the database

**Comment by cbeer** [comment]
coursereserves `updatedDate` is not an indexed field.

**Comment by thatbudakguy** [comment]
big step on this one is the first checkbox above (determining how many more things we need to add to the query). if the answer is "not too many and their tables are small", possible to add our needed indices to FOLIO's database

**Comment by shelleydoljack** [comment]
Does this help with finding updated records for courses?
```
select * from sul_mod_courses.coursereserves_courses where jsonb#>> '{metadata,updatedDate}' > '2023-04-01';
```

**Comment by jcoyne** [comment]
@shelleydoljack yes, but that's not going to give good performance at scale since it has to scan every row:
```
 EXPLAIN select * from sul_mod_courses.coursereserves_courses where jsonb#>> '{metadata,updatedDate}' > '2023-04-01' LIMIT 10;
                                     QUERY PLAN
-------------------------------------------------------------------------------------
 Limit  (cost=0.00..5.08 rows=10 width=578)
   ->  Seq Scan on coursereserves_courses  (cost=0.00..6.60 rows=13 width=578)
         Filter: ((jsonb #>> '{metadata,updatedDate}'::text[]) > '2023-04-01'::text)
```

**Comment by cbeer** [comment]
For stuff like course reserves, unless we can figure out a better way (or discover that FOLIO automatically touches something else with timestamps...), maybe we need a separate process to enqueue the items that runs less frequently.

**Comment by jcoyne** [comment]
|table_name|update column|indexed|
|-----------|---------------|--------|
|sul_mod_courses.coursereserves_courselistings|||
|sul_mod_courses.coursereserves_courses|||
|sul_mod_courses.coursereserves_reserves|||
|sul_mod_inventory_storage.call_number_type|||
|sul_mod_inventory_storage.holdings_record|||
|sul_mod_inventory_storage.holdings_type|||
|sul_mod_inventory_storage.ill_policy|||
|sul_mod_inventory_storage.instance|||
|sul_mod_inventory_storage.item|||
|sul_mod_inventory_storage.item_damaged_status|||
|sul_mod_inventory_storage.loan_type|||
|sul_mod_inventory_storage.location|?|?|
|sul_mod_inventory_storage.locinstitution|||
|sul_mod_inventory_storage.loccampus|||
|sul_mod_inventory_storage.loclibrary|||
|sul_mod_inventory_storage.material_type|||
|sul_mod_orders_storage.pieces|||
|sul_mod_orders_storage.titles|||
|sul_mod_source_record_storage.marc_records_lb|||
|sul_mod_source_record_storage.records_lb|||
