### ISSUE TITLE
Title fields punctuation stripping needs additional analysis

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#77]
(- is solrmarc, + is traject)
``` 
       -"title_245a_display" => ["The study of man."],
        +"title_245a_display" => ["The study of man"],

        -"title_display" => ["The study of man."],
        +"title_display" => ["The study of man"],
```

Also a7070581:

```
        -"vern_title_245c_display" => ["王建革著."],
        +"vern_title_245c_display" => ["王建革著"],
```

**Comment by shelleydoljack** [comment]
I don't think solrmarc's vern_title_245c_display is correct. The trailing period should be removed for 4 or more letters but the regex is `[A-Za-z]{4}` which I don't think includes non-Latin script. The regex for this field should have probably been `\p{InHiragana}|\p{InKatakana}|\p{IsHan}|\p{IsHangul}}{4}` (but that's only CJK, would also need to include the Unicode code blocks for Hebrew and Cyrillic). It appears that ruby's [[:word:]] character class includes non-Latin scripts.

**Comment by shelleydoljack** [comment]
The traject config currently puts "The study of man." (with period) into the solr field. I'm not sure why it's getting stripped.
