### ISSUE TITLE
Generate Aardvark format records for geoblacklight

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/searchworks_traject_indexer#770]
Blocked by #1380 

In versions after v4, geoblacklight uses the [Aardvark schema](https://opengeometadata.org/docs/ogm-aardvark) instead of the previous v1.0. In order to update Earthworks to v4 and beyond, we need to write records to solr in this format instead of the existing configuration in `geo_config.rb`.

This blocks https://github.com/sul-dlss/earthworks/issues/936.

See:
- [metadata mapping ISO19139 -> cocina -> Aardvark](https://docs.google.com/spreadsheets/d/1GV1QK04d870EM5ismR0iHef-9n5bIe5laP0VVjzq0FA/edit#gid=2042286233)
- [OGM notes about mapping between v1 format and Aardvark](https://opengeometadata.org/aardvark-gbl-1-crosswalk/)

After the mapping is settled, we need to:
- [x] move our existing 1.0 metadata in OGM to a v1.0-specific directory (or just delete it, since it won't get updated)*
- [ ] update [the script that populates our OGM repo](https://github.com/OpenGeoMetadata/edu.stanford.purl/blob/master/Rakefile) to publish Aardvark to an aardvark directory

*as of geoblacklight community meeting 1/10/24, there seems to be a consensus that there's no need to keep old/v1 records updated once you move to aardvark

**Comment by thatbudakguy** [comment]
Note that we need a working traject config to do this, but we **shouldn't do it in production** until we have upgraded geoblacklight to v4 (https://github.com/sul-dlss/earthworks/issues/936) because v3 won't be able to display our records.

**Comment by thatbudakguy** [comment]
Since this needs to be done in tandem with https://github.com/sul-dlss/earthworks/issues/936, one way to do it would be:

- [ ] review docs and decide on how to map fields from v3 to Aardvark
- [ ] update the `geo_config.rb`
- [ ] update the solr configset for earthworks
- [ ] create a new solr core and test indexing some SDR content into it using the new `geo_config.rb`
- [ ] after https://github.com/sul-dlss/earthworks/issues/936 is done, deploy EW to stage and point it at the new core

**Comment by thatbudakguy** [comment]
Another option is to stand up a local development instance of geoblacklight v4, and then index records into it and see how they display. This might be the quickest way to compare the GBL v1 and Aardvark versions of a record.

**Comment by edsu** [comment]
If it doesn't complicate things too much perhaps we could put this behind a feature flag?

**Comment by edsu** [comment]
I can't edit the description for some reason, but I think we want map from Cocina to Aardvark now? 

https://docs.google.com/spreadsheets/d/1GV1QK04d870EM5ismR0iHef-9n5bIe5laP0VVjzq0FA/edit#gid=2042286233

**Comment by thatbudakguy** [comment]
I updated the spreadsheet link; thanks @edsu!

**Comment by thatbudakguy** [comment]
created #1380, which blocks this
