### ISSUE TITLE
Ensure item data used for implementing request business logic are indexed

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#774]
FOLIO [circulation rules ](https://github.com/folio-org/mod-circulation/blob/cdf0b3c2bd2293004bdf259d0dc6c990a7ba672a/doc/circulationrules.md) use a variety of data to determine applicable policies:

- [x] N/A ~g the patron's patron group (like staff, undergrad, visitor)~
- [ ] `m` the item's material type (like book, newspaper)
- [ ] `t` the item's loan type (like rare, course-reserve) -- possibly unused at SUL
- [ ] `a` the item's institution (location)
- [ ] `b` the item's campus (location)
- [ ] `c` the item's library (location)
- [ ] `s` the item's location (location)

We should figure out where/how to index the appropriate item data for our ease of use. It's likely we'll want both a UUID and human-readable label for these.

(Related to https://github.com/sul-dlss/SearchWorks/issues/3100)
(Possibly related to https://github.com/sul-dlss/searchworks_traject_indexer/issues/714)

**Comment by jcoyne** [comment]
I don't know where exactly to find this material, but it looks like it might be derived from holding records.

```ruby
client = FolioClient.new(url: Utils.env_config.okapi_url)
record = client.source_record(instanceHrid: 'a14185492')
holding = record.holdings.first
```

* `m` may be `holding['holdingsType'] => 'Monograph'`
* `t` ?
* `a` may be `holding.dig('location', 'effectiveLocation', 'institutionName') => "Stanford University"`
* `b` may be `holding.dig('location', 'effectiveLocation', 'campusName') => "Stanford Libraries"`
* `c` may be `holding.dig('location', 'effectiveLocation', 'libraryName') => "Music"`
* `s` may be `holding.dig('location', 'effectiveLocation', 'name') => "Music Scores"`

**Comment by jcoyne** [comment]
I think this is already done? https://github.com/sul-dlss/searchworks_traject_indexer/blob/master/lib/traject/config/folio_config.rb#L194-L199

**Comment by corylown** [comment]
Confirmed, this information is in the `holdings_json_struct` field (which appears to include both items and holdings data):

```
irb(main):023:0> json['items'].first['location']
=> 
{"effectiveLocation"=>
  {"id"=>"4573e824-9273-4f13-972f-cff7bf504217",
   "code"=>"GRE-STACKS",
   "name"=>"Green Library Stacks",
   "campus"=>
    {"id"=>"c365047a-51f2-45ce-8601-e421ca3615c5",
     "code"=>"SUL",
     "name"=>"Stanford Libraries"},
   "details"=>nil,
   "library"=>
    {"id"=>"f6b5519e-88d9-413e-924d-9ed96255f72e",
     "code"=>"GREEN",
     "name"=>"Cecil H. Green"},
   "institution"=>
    {"id"=>"8d433cdd-4e8f-4dc1-aa24-8a4ddb7dc929",
     "code"=>"SU",
     "name"=>"Stanford University"}},
 "permanentLocation"=>
  {"id"=>"4573e824-9273-4f13-972f-cff7bf504217",
   "code"=>"GRE-STACKS",
   "name"=>"Green Library Stacks",
   "campus"=>
    {"id"=>"c365047a-51f2-45ce-8601-e421ca3615c5",
     "code"=>"SUL",
     "name"=>"Stanford Libraries"},
   "details"=>nil,
   "library"=>
    {"id"=>"f6b5519e-88d9-413e-924d-9ed96255f72e",
     "code"=>"GREEN",
     "name"=>"Cecil H. Green"},
   "institution"=>
    {"id"=>"8d433cdd-4e8f-4dc1-aa24-8a4ddb7dc929",
     "code"=>"SU",
     "name"=>"Stanford University"}},
 "temporaryLocation"=>nil}
irb(main):025:0> json['items'].first['permanentLoanType']
=> "Can circulate"
irb(main):032:0> json['items'].first['permanentLoanTypeId']
=> "2b94c631-fca9-4892-a730-03ee529ffe27"
irb(main):033:0> json['items'].first['materialType']
=> "book"
irb(main):030:0> json['items'].first['materialTypeId']
=> "1a54b431-2e4f-452d-9cae-9cee66c9a892"
```

**Comment by thatbudakguy** [comment]
We've confirmed the necessary data is indexed.
