### ISSUE TITLE
Figure out if we need to handle SDR coordinate locations

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#807]
In Folio, SDR objects are represented by multiple locations.

https://github.com/sul-dlss/folio_migration/pull/68

Are we using anything similar in Symphony, or do we always check the 856u?

There are now multiple "SDR" locations in here:
https://github.com/sul-dlss/folio_migration/blob/ad4145445f1189f5004916504f9de84b4d2caf35/mapping_files/locations.tsv

- Check if we're hardcoding `SUL-SDR` now and need to adapt to handling multiple locations?
- Find some things that have these locations and compare how they look in SW-prod vs SW-folio-dev

**Comment by thatbudakguy** [comment]
Currently in stage, but not test:

![Image](https://user-images.githubusercontent.com/4924494/235504900-c231f1e0-2028-4bf5-886d-2c9a776fd97e.png)

Blocked until records in test are refreshed.

**Comment by thatbudakguy** [comment]
Possible that #767 will make this work?
