### ISSUE TITLE
Treat MarcLinks::GSB_URL_REGEX matching URLs consistently

### ISSUE THREAD

**Issue by corylown** [sul-dlss/searchworks_traject_indexer#864]
Currently we filter out links that match `MarcLinks::GSB_URL_REGEX` from the `url_fulltext` field and when building holdings for e-resources in Folio::EresourceHoldingsBuilder. However, we do not exclude URLs that match `MarcLinks::GSB_URL_REGEX` from being labeled `fulltext` in `MarcLinks::Processor`. We should determine whether or not this is still an issue and apply this filter consistently if it is and remove it if it's no longer relevant.

**Comment by cbeer** [comment]
Jeanette + Irina confirmed we don't have any matching the original VUF-230 use case.. so I think we can rip it out.
