### ISSUE TITLE
[searchworks_traject_indexer/stage] NoMethodError: undefined method `fetch' for nil:NilClass

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#884]
## Backtrace

    line 18 of [PROJECT_ROOT]/lib/folio/mhld_builder.rb: block in build
    line 17 of [PROJECT_ROOT]/lib/folio/mhld_builder.rb: map
    line 17 of [PROJECT_ROOT]/lib/folio/mhld_builder.rb: build

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/57331/faults/95841937)

**Comment by jcoyne** [comment]
It seems like our SQL query is not returning location for this holding record in the way the API returns it.
![Screenshot 2023-05-18 at 11 33 39 AM](https://github.com/sul-dlss/searchworks_traject_indexer/assets/92044/366c0709-db9e-4f91-a622-ab09e1b172fc)
![Screenshot 2023-05-18 at 11 34 11 AM](https://github.com/sul-dlss/searchworks_traject_indexer/assets/92044/780aa8ec-b458-41e6-b9d9-fde5093bcd7d)
