### ISSUE TITLE
Use FOLIO's discovery labels

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#896]
There's also an opportunity to use labels from various tables instead of maintaining a code->user label mapping in Searchworks:
- [ ] `sul_mod_inventory_storage.location`  
- [ ] `sul_mod_inventory_storage.loclibrary`

If we can use those mappings, I think we have a choice whether to fetch them at query time or store them in this project and update them regularly.

If we fetch them at query time, it'll be important for consistency to reindex the instance data if/when the labels change (e.g. to avoid having the same library show up multiple times in the library facet (`building_facet` field))

If we decide to stash them in the project, we'll need a process for retrieving the data and kicking off a full reindex.

**Comment by jcoyne** [comment]
@cbeer it looks to me like we're already fetching the discovery labels at query time. Is the first part of this already done?

https://github.com/sul-dlss/searchworks_traject_indexer/blob/main/lib/traject/readers/folio_postgres_reader.rb#L99-L102

**Comment by cbeer** [comment]
I don't think we're doing anything with those labels, are we? As far as I can tell at a glance, we're still using the library + location code translation maps (which is good.. because we definitely need to figure out how to ensure a consistent index + display to our users before switching.)

**Comment by jcoyne** [comment]
@cbeer should this become an "after folio" task?

**Comment by cbeer** [comment]
Is there a good reason it needs to be? We're expecting the library + location discovery labels to be pretty close to parity (and  need to use them in Searchworks, Requests, and MyLibrary for launch, because we'll have new location codes that don't have existing translations, e.g. for Lane). At the very least, it seems like we need to do the "generate a traject translation map from the discovery labels and stash them in the project" option.

**Comment by jcoyne** [comment]
Since we can't find a performant query without a arch change, we'll need to synchronize the labels.

**Comment by jcoyne** [comment]
I notice that the label from Folio is "Robert Crown Law", but the label we use in the building facet currently is "Law (Crown)".  Is this change acceptable?
