### ISSUE TITLE
Work with stakeholders to define an acceptable FOLIO instance data -> MARC mapping for searchworks

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#897]
We made up our own mapping (inspired by the MARC -> FOLIO instance mapping):
https://github.com/sul-dlss/searchworks_traject_indexer/blob/master/lib/folio_record.rb#L178-L235

There's room for improvement:

- [ ] https://github.com/sul-dlss/searchworks_traject_indexer/issues/1047

**Comment by thatbudakguy** [comment]
Need to talk to @ahafele to figure out where we can do better (probably at least in the areas of on-order and course reserve items).

**Comment by cbeer** [comment]
Here's our existing mapping in spreadsheet form:
https://docs.google.com/spreadsheets/d/1o_aEprUWBC2Yyecr9WfNHXtZFPn1cjIlg-k3URidve0/edit?usp=sharing
