### ISSUE TITLE
Update FOLIO MHLD indexing for parity with Symphony indexing

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/searchworks_traject_indexer#898]
- [x] Include public notes with the supplement + index holdings statements, currently concatenated using the `library_has` helper (https://github.com/sul-dlss/searchworks_traject_indexer/blob/master/lib/traject/config/sirsi_config.rb#L2506)
- [ ] ~Only include the latest received and holdings level note from the 852 once (new behavior in #874). [(existing test)](https://github.com/sul-dlss/searchworks_traject_indexer/blob/master/spec/lib/traject/config/holdings_spec.rb#L385-L391)~
- [ ] ~Omit the latest received if the series is "closed" (or.. [something about the 852$=](https://github.com/sul-dlss/searchworks_traject_indexer/blob/master/spec/lib/traject/config/holdings_spec.rb#L543-L553))~
- [x] ~Filter out MHLDs with "All holdings transferred"~ (not being migrated to FOLIO)
- [ ] Backfill some MHLDBuilder tests?

Instead of including latest received information based on MARC field content (e.g. `852$=`, an 867 + 868, or an open series in the 866), FOLIO has some native properties we've been asked to use:

- [x] electronic holdings never show latest received (holdingsType = electronic)
- [x] index the latest received statement if:
         - the `holdingsType = serial` (migration still in progress. filtering holdingsType = electronic is good enough to get started)
         - the order/holding-summary has an orderType = ongoing and orderStatus = open

**Comment by thatbudakguy** [comment]
waiting on SRS loading to be complete to start this.

**Comment by jcoyne** [comment]
Regarding "display the latest received statement if:" Should this be in searchworks? or do we mean "only index the received statement if..."

**Comment by corylown** [comment]
Documenting some things as I go:

Record a567006 has a latest received in searchworks prod:
https://searchworks.stanford.edu/view/567006

a567006 doesn't have a latest received in searchworks-folio-dev: https://searchworks-folio-dev.stanford.edu/view/567006 -- the reason appears to be that the latest received is on a separate holding and that holding lacks any holdings statements. I can't tell if this is a data migration error or if this is what we should expect in FOLIO and need to adjust something.

Lots of records appear to be missing pieces data, which is where we're fetching chronology.

**Comment by corylown** [comment]
Well, this explains a lot (ids refer to holdings on a567006):

> 9123d1f6-faec-5483-a488-b51907965326 is a MARC-backed holding and 6c98c0a1-3a28-5ba2-80e1-d6f86e284686 is a folio holding. After much debate and discussion, it was decided that we will migrate MARC holdings to FOLIO in addition to having a FOLIO holding because it is difficult to programmatically merge the two.  The long-term plan is that staff will be manually moving “library has” statements and public notes from 852|z from MARC-backed holdings to FOLIO holdings and deleting them from MARC-backed holdings. So my understanding is that the SearchWorks should display all holdings statements and all holding statement public notes, regardless of which holding they are coming from. As to the receiving pieces, I am only adding them to the FOLIO holding, there shouldn’t be any MARC-backed holdings with receiving history.

**Comment by corylown** [comment]
I think we need some refactoring in MhldBuilder to assemble a single mhld_display value for each library/location, but with values assembled from any available holding record (to account for the MARC and FOLIO versions mentioned above). Right now the code is filtering out any holdings that don't have summaries, but the piece information we're using to assemble latest-received is attached to holdings without summaries, so we can't throw them away.
