### ISSUE TITLE
Enumeration not present in call number in item_display for Bound-withs

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/searchworks_traject_indexer#904]
Breaking this out so as not to block #894

The child call number in production is `630.654 .I39M V.5:NO.2`. Using data from our DB query, the displayed call number is `630.654 .I39M`. From FOLIO we currently don't have child's callnumber data that supplies the `V.5:NO.2` enumeration. This may also be taking place in other series that aren't Bound-withs, but that needs investigation.

Record: https://searchworks.stanford.edu/view/2279186

See Local
![Screenshot 2023-05-22 at 16 01 18](https://github.com/sul-dlss/searchworks_traject_indexer/assets/1328900/bf43da45-be10-4e17-9f91-177a50951559)

vs. Production
![Screenshot 2023-05-22 at 16 03 30](https://github.com/sul-dlss/searchworks_traject_indexer/assets/1328900/c7119b91-eeb3-4f30-8c3f-321a2d7512c1)

**Comment by shelleydoljack** [comment]
The enumeration is in the tsv file:
```
sirsi@bodoni /s/SUL/Dataload/folio_symphony_extract/Bibs/Bibs_catdumps> grep 2279186 ckeys_02250000_02299999.tsv.bwchild.tsv
2279186	2	1	36105026515499	SAL3	SEE-OTHER	SEE-OTHER	STKS-MONO	BW-CHILD		0	1DEWEY	630.654 .I39M	V.5:NO.2	0	MARC	0
```

**Comment by shelleydoljack** [comment]
@jermnelson I'm not sure where to create a ticket, if this is breaking in folio_migration or libsys-airflow. The `VOLUME_INFO` column from the tsv did map to holdings call number at some point (I recall showing it in a folio first friday presentation). In any case, this data needs to make it to the bw child folio holdings record.

**Comment by jermnelson** [comment]
@shelleydoljack  the `VOLUME_INFO` column isn't included in the https://github.com/sul-dlss/libsys-airflow/blob/6a6bb9edc5ef9185d04f6a3f8caaf3f30fb9d259/libsys_airflow/plugins/folio/holdings.py#L491-L504 holdings bw code so I think the issue should be created in the libsys_airflow. Are there other columns that should be included as well?

**Comment by shelleydoljack** [comment]
@ahafele where in the folio holdings record should the bw child enumeration go? Do we simply concatenate it with the call number in holdings.callNumber? Was there a decision on where to put the bw child item xinfo notes; not quite related but somewhat since it is a field that normally would map to the folio item record?

**Comment by shelleydoljack** [comment]
Ticketed: https://github.com/sul-dlss/libsys-airflow/issues/691

**Comment by thatbudakguy** [comment]
need to check on state of data; maybe resolved now?

**Comment by shelleydoljack** [comment]
We plan to do an extract starting July 6 for loading to folio-prod July 8. Should double-check what the holdings call number looks like for these in folio-prod once loaded.

**Comment by shelleydoljack** [comment]
Fix in latest production migration
![Screen Shot 2023-07-10 at 12 44 29 PM](https://github.com/sul-dlss/searchworks_traject_indexer/assets/6343464/601ccb45-d754-450f-a58e-c8696376dbb3)

**Comment by cbeer** [comment]
Closing this, but noting the data in -test lags behind the data in -prod.
