### ISSUE TITLE
index online/electronic material at parity with Symphony

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#923]
Our FOLIO searchworks index is missing most/all online material; presumably it's being filtered out by https://github.com/sul-dlss/searchworks_traject_indexer/blob/main/lib/traject/config/sirsi_config.rb#L2424

We did previous work on electronic resources in #858

Examples catkeys that we expect should be in the index:

```
10083185
10150380
10092538
12014558
```

**Comment by corylown** [comment]
I would expect `12014558` to be present -- it doesn't get filtered out when I run it through Traject. The other three (`10083185`, `10150380`, `10092538`) are missing source records. I don't think we're looking anywhere other than the source record's MARC 856 for links. The work here may be to figure out how to get link data out of `record.instance['electronicAccess']`.

**Comment by cbeer** [comment]
Ah, ok. maybe the SRS load still isn't finished 😬
