### ISSUE TITLE
Index FOLIO item status information for parity

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#937]
We need to map some FOLIO item statuses to information in the `item_display` field:

- [x] 'In Process' should set the current location to INPROCESS (e.g. a14644326, a14540777)
- [x] 'Missing' => 'MISSING' (e.g. a3118108)
- [x] 'Long missing' => 'MISSING'
- [x] 'In transit' => 'INTRANSIT'
- [x] 'Checked out' => 'CHECKEDOUT' 
- [x] ~~'Claims returned'~~ 'Claimed returned' => 'CHECKEDOUT'
- [x] 'Aged to lost' => 'CHECKEDOUT'
- [x]  Other values?

**Comment by corylown** [comment]
Other possible mappings are:

'On order' => 'ON-ORDER'
'In process (non-requestable)' => 'AT-REPAIR' or 'BINDERY' (or other BIND code)
'Awaiting pickup' => "#{library_code}-LOAN" (but how to know at which service desk?)
'Awaiting pickup' => "#{library_code}-LOAN" (but how to know at which service desk?)

**Comment by cbeer** [comment]
I haven't run into an On order or In process (non-requestable) item statuses in FOLIO yet, but mapping to `ON-ORDER` and `INPROCESS` makes sense to me 🤷‍♂️ 

I think most (all?) the -LOAN map to the same underlying text ("On hold for a borrower"). It looks like the Request object might be the only thing that knows: https://github.com/folio-org/mod-circulation/blob/32610de6b29dc17badf6ed4f6a392881526031ac/src/main/java/org/folio/circulation/domain/UpdateRequestQueue.java#L150... but maybe it's enough to map to a generic code and deal with the exceptions later?
