### ISSUE TITLE
Map SUL/SDR location to SUL/INTERNET for parity

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#938]
Some electronic holdings in FOLIO have the location code SUL-SDR, but in Symphony were in SUL/INTERNET.

**Comment by jcoyne** [comment]
Is there a sample record we are looking at? Which field in Solr needs to change?

**Comment by cbeer** [comment]
Here's one:

https://searchworks-folio-dev.stanford.edu/view/10146027

and you can find many more in FOLIO:
<img width="266" alt="Screenshot 2023-07-05 at 12 52 48" src="https://github.com/sul-dlss/searchworks_traject_indexer/assets/111218/4bc92f38-d24e-48ae-995d-85c1bfd40b13">

https://folio-test.stanford.edu/inventory?filters=holdingsPermanentLocation.1b14e21c-8d47-45c7-bc49-456a0086422b&query=SUL%20SDr&segment=holdings&sort=title

I'd expect the compare_sirsi_and_folio_spec to pass for that record ([currently marked as pending](https://github.com/sul-dlss/searchworks_traject_indexer/blob/main/spec/integration/compare_sirsi_and_folio_spec.rb#L182))

**Comment by jcoyne** [comment]
https://folio-test.stanford.edu/inventory?filters=holdingsPermanentLocation.1b14e21c-8d47-45c7-bc49-456a0086422b&segment=holdings&sort=title seems to work better.
