### ISSUE TITLE
Database records and the SW facet

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/searchworks_traject_indexer#948]
Metadata staff raised that, from their understanding, we currently place records into the Database facet by looking in the marc tags (008, maybe others) OR looking for a Symphony Item Type = DATABASE. Looking at records, it appears adding the Symphony Item Type is often the "preferred" way for metadata staff to add the record to the Database facet.

Symphony Item Types are moving to FOLIO Instance level "Statistical code", therefore we should start looking for a FOLIO statistical code = `database`, and add the record to the Resource Type "Database" facet.

Currently we don't have example or migrated records that have a statistical code = `database` in folio-test. Work to add the statistical code to migrated data is described in https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/416#issuecomment-1588200537. 

Originally was described by Alissa here: https://github.com/sul-dlss/FOLIO-Project-Stanford/issues/415

Noting from Alissa's original ticket that the Database A-Z list should be fine as those topics are generated from the 099 marc tag, and will continue to be populated there after the move to FOLIO.

**Comment by saseestone** [comment]
@ahafele or @dlrueda would it be problematic to create statistical code = `database` on folio-test, and then add it to a few example records (particularly records that don't have a marc 008 identifying them as a database)? 

I'm happy to do the work of creating the example records based on examples currently in Symphony,  but want to make sure that I wouldn't be causing any issues by doing so.

**Comment by ahafele** [comment]
@saseestone I'm happy to do this. Can you tell me what the SW code looks for in the 008 or otherwise to identify as a database? In the meantime, Database Instance stat code has been added to: 
a14393458
a13863317
a13142751
a12086488
