### ISSUE TITLE
Do something to suppress symphony-shadowed items

### ISSUE THREAD

**Issue by thatbudakguy** [sul-dlss/searchworks_traject_indexer#949]
tentative implementation for this: don't index items that are in special "migration error" location in FOLIO (have a location name like `GREEN-MIGRATION-ERR`, etc.

this should exclude things that are shadowed in symphony, which are in locations that don't get mapped (and thus end up in the "migration error" bin now).

**Comment by saseestone** [comment]
LibSys Location mappings are: https://github.com/sul-dlss/folio_migration/blob/main/mapping_files/locations.tsv. Examples are:


ARS-MIGRATE-ERR
ART-MIGRATE-ERR
BUS-MIGRATE-ERR
CLA-MIGRATE-ERR
