### ISSUE TITLE
Handling awaiting + in-transit statuses with more specific information

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/searchworks_traject_indexer#974]
In Symphony, we have `*-LOAN` locations (meaning e.g. at the Green Loan desk). We generally map those to "On hold for a borrower", but there are some library-specific exceptions (ARS, RUMSEY).

In #973, we mapped to a generic code, but we should see if there's anything more we can do to reach parity.

Work with Darsi as needed to make an item go through FOLIO paging to become "Awaiting Pickup"

**Comment by saseestone** [comment]
Some items that I made "Awaiting Pickup" using folio processes:

1. https://searchworks-folio-dev.stanford.edu/view/645342
2. https://searchworks-folio-dev.stanford.edu/view/645341

And one that is "Paged":
3. https://searchworks-folio-dev.stanford.edu/view/1364605

I was trying to get one that is "In transit" for you, but couldn't quickly. As mentioned, Darsi or @ahafele may be able to help based on their knowledge about material tracking.

**Comment by corylown** [comment]
At first glance, it doesn't look like there's anything on the item record that will tell was where the item actually is when it's has one of these item states. We'd have to lookup the request, I think.

**Comment by ahafele** [comment]
in-transit: https://folio-test.stanford.edu/inventory?filters=itemStatus.In%20transit&segment=items&sort=title
